version: '3.8'

services:
  totp-generator:
    build: .
    container_name: google-totp-generator
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GOOGLE_TOTP_SECRET=pumx4n26255yb52amsatqytkfjxbcrql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - totp-network

networks:
  totp-network:
    driver: bridge
